In [204]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [205]:
df = pd.read_csv('corona_tested_individuals_ver_006.english.csv')
df

D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (1,2,3,4,5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


test_date cough fever sore_throat shortness_of_breath head_ache  \
0       2020-04-30     0     0           0                   0         0   
1       2020-04-30     1     0           0                   0         0   
2       2020-04-30     0     1           0                   0         0   
3       2020-04-30     1     0           0                   0         0   
4       2020-04-30     1     0           0                   0         0   
...            ...   ...   ...         ...                 ...       ...   
278843  2020-03-11     0     0           0                   0         0   
278844  2020-03-11     0     0           0                   0         0   
278845  2020-03-11     0     0           0                   0         0   
278846  2020-03-11     0     0           0                   0         0   
278847  2020-03-11     0     0           0                   0         0   

       corona_result age_60_and_above  gender         test_indication  
0           negative             None  female                   Other  
1           negative             None  female                   Other  
2           negative             None    male                   Other  
3           negative             None  female                   Other  
4           negative             None    male                   Other  
...              ...              ...     ...                     ...  
278843      negative             None    None                   Other  
278844      negative             None    None                   Other  
278845      positive             None    None  Contact with confirmed  
278846         other             None    None                   Other  
278847      negative             None    None                   Other  

[278848 rows x 10 columns]

In [206]:
df_copy = df.copy()

In [207]:
df.drop(['test_date'], axis=1, inplace=True)

In [208]:
df

cough fever sore_throat shortness_of_breath head_ache corona_result  \
0          0     0           0                   0         0      negative   
1          1     0           0                   0         0      negative   
2          0     1           0                   0         0      negative   
3          1     0           0                   0         0      negative   
4          1     0           0                   0         0      negative   
...      ...   ...         ...                 ...       ...           ...   
278843     0     0           0                   0         0      negative   
278844     0     0           0                   0         0      negative   
278845     0     0           0                   0         0      positive   
278846     0     0           0                   0         0         other   
278847     0     0           0                   0         0      negative   

       age_60_and_above  gender         test_indication  
0                  None  female                   Other  
1                  None  female                   Other  
2                  None    male                   Other  
3                  None  female                   Other  
4                  None    male                   Other  
...                 ...     ...                     ...  
278843             None    None                   Other  
278844             None    None                   Other  
278845             None    None  Contact with confirmed  
278846             None    None                   Other  
278847             None    None                   Other  

[278848 rows x 9 columns]

In [209]:
feature_columns = [ col for col in df.columns if col!= 'corona_result']
feature_columns

['cough',
 'fever',
 'sore_throat',
 'shortness_of_breath',
 'head_ache',
 'age_60_and_above',
 'gender',
 'test_indication']

In [210]:
for col in feature_columns:
    print(col)
    print(df[col].unique().tolist())
    print("*"*100)

cough
[0, 1, '0', '1', 'None']
****************************************************************************************************
fever
[0, 1, '0', '1', 'None']
****************************************************************************************************
sore_throat
[0, 1, '0', '1', 'None']
****************************************************************************************************
shortness_of_breath
[0, 1, '0', '1', 'None']
****************************************************************************************************
head_ache
[0, 1, '0', '1', 'None']
****************************************************************************************************
age_60_and_above
['None', 'Yes', 'No']
****************************************************************************************************
gender
['female', 'male', 'None']
****************************************************************************************************
test_indication
['Other', 'Abroad', 'Cont

In [211]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278848 entries, 0 to 278847
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   cough                278848 non-null  object
 1   fever                278848 non-null  object
 2   sore_throat          278848 non-null  object
 3   shortness_of_breath  278848 non-null  object
 4   head_ache            278848 non-null  object
 5   corona_result        278848 non-null  object
 6   age_60_and_above     278848 non-null  object
 7   gender               278848 non-null  object
 8   test_indication      278848 non-null  object
dtypes: object(9)
memory usage: 19.1+ MB


In [212]:
for col in feature_columns:
    df[col].replace({'None': np.nan}, inplace=True)
df.isnull().sum()

cough                     252
fever                     252
sore_throat                 1
shortness_of_breath         1
head_ache                   1
corona_result               0
age_60_and_above       127320
gender                  19563
test_indication             0
dtype: int64

In [213]:
# dropping cough, fever, sorethroat, head_ache, shortness_of_breath null values
df.dropna(subset=['cough', 'fever', 'sore_throat', 'shortness_of_breath', 'head_ache'],inplace=True)

In [214]:
df.isna().sum()

cough                       0
fever                       0
sore_throat                 0
shortness_of_breath         0
head_ache                   0
corona_result               0
age_60_and_above       127315
gender                  19552
test_indication             0
dtype: int64

In [215]:
df['age_60_and_above'].fillna(value='No', inplace=True)

In [216]:
df.isna().sum()

cough                      0
fever                      0
sore_throat                0
shortness_of_breath        0
head_ache                  0
corona_result              0
age_60_and_above           0
gender                 19552
test_indication            0
dtype: int64

In [217]:
df = df.astype({'cough': int, 'fever': int, 'sore_throat': int, 'shortness_of_breath': int, 'head_ache': int})

In [218]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 278594 entries, 0 to 278847
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   cough                278594 non-null  int32 
 1   fever                278594 non-null  int32 
 2   sore_throat          278594 non-null  int32 
 3   shortness_of_breath  278594 non-null  int32 
 4   head_ache            278594 non-null  int32 
 5   corona_result        278594 non-null  object
 6   age_60_and_above     278594 non-null  object
 7   gender               259042 non-null  object
 8   test_indication      278594 non-null  object
dtypes: int32(5), object(4)
memory usage: 15.9+ MB


In [219]:
df.shape

(278594, 9)

In [220]:
# one hot encoding for model buidling
df['corona_result'].unique()

array(['negative', 'positive', 'other'], dtype=object)

In [221]:
df['corona_result'].replace({'negative': 0, 'positive': 1, 'other': 2}, inplace=True)

In [222]:
df['age_60_and_above'].replace({'No': 0, 'Yes': 1}, inplace=True)

In [223]:
df['test_indication'].replace({'Other': 0, 'Abroad': 1,'Contact with confirmed': 2}, inplace=True)

In [224]:
df['gender'].replace({'female': 0, 'male': 1}, inplace=True)

In [225]:
df.dropna(inplace=True)

In [226]:
df.isna().sum()

cough                  0
fever                  0
sore_throat            0
shortness_of_breath    0
head_ache              0
corona_result          0
age_60_and_above       0
gender                 0
test_indication        0
dtype: int64

In [227]:
df.shape

(259042, 9)

In [228]:
df.describe().T

count      mean       std  min  25%  50%  75%  max
cough                259042.0  0.153083  0.360068  0.0  0.0  0.0  0.0  1.0
fever                259042.0  0.077956  0.268104  0.0  0.0  0.0  0.0  1.0
sore_throat          259042.0  0.005864  0.076351  0.0  0.0  0.0  0.0  1.0
shortness_of_breath  259042.0  0.004243  0.064997  0.0  0.0  0.0  0.0  1.0
head_ache            259042.0  0.008215  0.090263  0.0  0.0  0.0  0.0  1.0
corona_result        259042.0  0.078288  0.313384  0.0  0.0  0.0  0.0  2.0
age_60_and_above     259042.0  0.092958  0.290374  0.0  0.0  0.0  0.0  1.0
gender               259042.0  0.498035  0.499997  0.0  0.0  0.0  1.0  1.0
test_indication      259042.0  0.166548  0.462605  0.0  0.0  0.0  0.0  2.0

In [229]:
# model Building
# Neural Network for multiclass prediction
# Multiclass Preceptron Model

In [230]:
def sigmoid(z):
    z = np.array(z)
    return 1/(1+np.exp(-z))

In [231]:
def sigmoid_gradient(z):
    z = np.array(z)
    return sigmoid(z) * (1-sigmoid(z))

In [232]:
len(feature_columns)

8

In [233]:
input_layer_size = 8
hidden_layer_size = 5
num_labels = 3
lambda_r = 1

In [234]:
def random_initilization(input_layer_size, hidden_layer_size, num_labels):
    e = 0.12
    initial_theta1 = np.random.uniform(low=-e, high=e, size=(hidden_layer_size, input_layer_size+1))
    initial_theta2 = np.random.uniform(low=-e, high=e, size=(num_labels, hidden_layer_size+1))
    return initial_theta1, initial_theta2

In [235]:
# def nn_cost_function(nn_params, input_layer_size, hidden_layer_size, num_labels, X, y, lambda_r):
#     theta1 = np.reshape(nn_params[:hidden_layer_size*(input_layer_size+1)], newshape=(hidden_layer_size, input_layer_size+1), order='F')
#     theta2 = np.reshape(nn_params[hidden_layer_size*(input_layer_size+1):], newshape=(num_labels, hidden_layer_size+1), order='F')
#     m = X.shape[0]
#     K = num_labels
#     capital_delta1 = np.zeros(theta1.shape)
#     capital_delta2 = np.zeros(theta2.shape)
#     X = np.hstack((np.ones((m,1)), X))
#     J = 0    
#     for i in range(m):
#         a1 = X[i]
#         z2 = a1.dot(theta1.T) #
#         a2 = sigmoid(z2) # sigmoid will give us probability / hidden layer output
#         a2 = np.hstack([1, a2])
#         z3 = a2.dot(theta2.T)
#         a3 = sigmoid(z3) # final layer output
#         h = a3
        
#         yk = np.zeros((K, 1))
#         yk[y[i, 0]-1, 0] = 1
#         j = (-yk.T.dot(np.log(h).T)-(1-yk).T.dot(np.log(1-h).T)) # cost function each class
#         J = J + (j/m) # sum of i
        
#         delta3 = a3 - yk.T
#         print("Delta3 ->", delta3.shape)
#         z2 = np.hstack([1, z2])
#         delta2 = theta2.T.dot(delta3.T) * (sigmoid_gradient(z2).reshape(-1, 1))
#         print("Delta2 ->", delta3.shape)
#         capital_delta1 = capital_delta1 + (delta2[1:, :].dot(a1.reshape(1, -1)))
#         capital_delta2 = capital_delta2 + delta3.T.dot(a2.reshape(1, -1))
        
#     sum1 = np.sum(np.sum(theta1[:, 1:]**2))
#     sum2 = np.sum(np.sum(theta2[:, 1:]**2))    
#     J = J + (lambda_r/(2*m))*(sum1+sum2)
    
#     grad_theta1 = (1/m)*(capital_delta1+lambda_r*theta1)
#     grad_theta1[:, 0] = ((1/m)*capital_delta1)[:, 0]
    
#     grad_theta2 = (1/m)*(capital_delta2 + lambda_r * theta2)
#     grad_theta2[:, 0] = ((1/m)*capital_delta2)[:,0]
    
#     grad_theta = np.hstack((grad_theta1.ravel(order='F'), grad_theta2.ravel(order='F')))
#     return J, grad_theta

In [236]:
def nn_cost_function(nn_params, input_layer_size, hidden_layer_size, num_labels, X, y, lambda_r):
    
    theta1 = np.reshape(nn_params[:hidden_layer_size * (input_layer_size+1)], newshape=(hidden_layer_size, input_layer_size+1), order='F')
    theta2 = np.reshape(nn_params[hidden_layer_size * (input_layer_size+1):], newshape=(num_labels, hidden_layer_size+1), order='F')
    
    m = X.shape[0]
    J = 0
    
    K = num_labels
    X = np.hstack((np.ones((m,1)),X)) #add bias unit

    capital_delta1 = np.zeros(theta1.shape)
    capital_delta2 = np.zeros(theta2.shape)
    
    for i in range(m):
        a1 = X[i]
#         print(a1.shape)
        z2 = a1.dot(theta1.T)
        a2 = sigmoid(z2)
        a2 = np.hstack([1, a2]) ##add bias unit
        
        z3 = a2.dot(theta2.T)
        a3 = sigmoid(z3)
        
        h = a3
        
        yk = np.zeros((K,1)) ##y is as K-dimensional vector
        yk[y[i,0], 0] = 1
        
        j = (-yk.T.dot(np.log(h).T) - (1-yk).T.dot(np.log(1-h).T)) ##sum of K
        J = J + (j/m) #sum of i
        
        delta3 = a3 - yk.T
        
        z2 = np.hstack([1, z2])
        delta2 = theta2.T.dot(delta3.T) * (sigmoid_gradient(z2).reshape(-1,1))
        
        capital_delta1 = capital_delta1 + (delta2[1:,:].dot(a1.reshape(1,-1)))
        capital_delta2 = capital_delta2 + (delta3.T.dot(a2.reshape(1,-1)))
        
    sum1 = np.sum(np.sum(theta1[:, 1:] ** 2))
    sum2 = np.sum(np.sum(theta2[:, 1:] ** 2))
    J = J + (lambda_r / (2*m)) * (sum1 + sum2)
    
    theta1_grad = (1/m) * (capital_delta1 + lambda_r * theta1) #with regularization
    theta1_grad[:,0] = ((1/m) * capital_delta1)[:,0]
    
    theta2_grad = (1/m) * (capital_delta2 + lambda_r * theta2) #with regularization
    theta2_grad[:,0] = ((1/m) * capital_delta2)[:,0]
    
    grad = np.hstack(( theta1_grad.ravel(order='F'), theta2_grad.ravel(order='F')))
    return J, grad

In [237]:
def compute_numerical_gradient(theta, input_layer_size, hidden_layer_size, num_labels, X, y, lambda_r):
    e = 0.0001
    num_grad = np.zeros(theta.shape)
    perturb = np.zeros(theta.shape)
    for p in range(len(theta)):
        perturb[p] = e
        loss1, _ = nn_cost_function(theta-perturb, input_layer_size, hidden_layer_size, num_labels, X, y, lambda_r)
        loss2, _ = nn_cost_function(theta+perturb, input_layer_size, hidden_layer_size, num_labels, X, y, lambda_r)
        num_grad[p] = (loss2-loss1)/(2*e)
        perturb[p] = 0
    return num_grad

In [238]:
def debug_initialize_weights(fan_out, fan_in):
    W = np.zeros((fan_out, 1+fan_in))
#     print(W)
#     print(np.reshape(range(len(W.ravel(order='F'))), W.shape))
    W = np.reshape(range(len(W.ravel(order='F'))), W.shape)/10
#     print(W)
    return W

In [239]:
def check_nn_gradients(lambda_r=0):
    input_layer_size = 3
    hidden_layer_size = 5
    num_labels = 3
    m = 5
    
    theta1 = debug_initialize_weights(hidden_layer_size, input_layer_size)
    theta2 = debug_initialize_weights(num_labels, hidden_layer_size)
    
    X = debug_initialize_weights(m, input_layer_size-1)
#     print(X)
    y = 1 + np.mod(range(m), num_labels).reshape(-1, 1)
#     print(y)
    nn_params = np.hstack((theta1.ravel(order='F'), theta2.ravel(order='F')))
    
    cost, grad = nn_cost_function(nn_params, input_layer_size, hidden_layer_size, num_labels, X, y, lambda_r)
    num_grad = compute_numerical_gradient(nn_params, input_layer_size, hidden_layer_size, num_labels, X, y, lambda_r)
    
    print('The columns should be very similar...')
    for i, j in zip(num_grad, grad):
        print(i,j)
        
    diff = np.linalg.norm(num_grad-grad)/np.linalg.norm(num_grad+grad)
    if diff < 0.000000010:
        print('\nBackpropagation is correct')
    else:
        print('\nBackpropagation is incorrect')

In [240]:
check_nn_gradients()

IndexError: index 3 is out of bounds for axis 0 with size 3

In [241]:
X = df[feature_columns].values
y = np.array(df['corona_result'].values).reshape(-1,1)


In [242]:
initial_theta1, initial_theta2 = random_initilization(input_layer_size, hidden_layer_size, num_labels)
nn_params = np.hstack((initial_theta1.ravel(order='F'), initial_theta2.ravel(order='F')))

In [192]:
import scipy.optimize as opt
lambda_r = 1
opt_results = opt.minimize(nn_cost_function, nn_params, args=(input_layer_size, 
                                                              hidden_layer_size, 
                                                              num_labels, 
                                                              X, 
                                                              y, 
                                                              lambda_r), 
                            method='L-BFGS-B', jac=True, options={'maxiter':50})

KeyboardInterrupt: 

In [245]:
from sklearn.neural_network import MLPClassifier
nn = MLPClassifier(hidden_layer_sizes=(hidden_layer_size,), activation='logistic', solver='lbfgs', alpha=1, max_iter=10)
nn.fit(X, y.T[0])

D:\Anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(activation='logistic', alpha=1, hidden_layer_sizes=(5,),
              max_iter=10, solver='lbfgs')

In [247]:
nn.score(X, y.T[0])

0.9439009890288061

In [248]:
predicted_y = nn.predict(X)

In [249]:
predicted_y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [250]:
y.T[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [251]:
np.mean(predicted_y == y.T[0])*100

94.39009890288061

In [256]:
X[0]

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [267]:
cough = 0
fever = 0 
sore_throat = 0
shortness_of_breath = 0 
head_ache = 0
age_60_and_above = 0 
gender = 1
test_indication = 0

In [268]:
new_x = np.array([cough, fever, sore_throat, shortness_of_breath, head_ache, age_60_and_above, gender, test_indication])
new_x

array([0, 0, 0, 0, 0, 0, 1, 0])

In [269]:
new_y = nn.predict(new_x.reshape(1,-1))

In [270]:
new_y

array([0], dtype=int64)

In [ ]:
def COVIDChatbot():
    chatBotName = "COVBOT"
    print(chatBotName +" : Hey There")
    while True:
        userInput = input()
        print("User : "+userInput)
        userInputList = userInput.lower().split(" ")
        print(userInputList)
        greeting_words = ['hey', 'hello', 'hi']
        for gw in greeting_words:
            if gw in userInputList:
                print(chatBotName +" : Hey There, what can i do for you today?")
            else:
                print(chatBotName +" : Ok I will ask you some questions to check if you are positive or not")
                counter = 0
                userInputDict = {}
                userQuestionDisct = {'cough':'Do you have any cough?',
                               'fever':'Do you have fever?', 
                               'sore_throat':'Do you have sore throat?',
                               'shortness_of_breath':'Do you have shprtness of breath?', 
                               'head_ache':'Is your head aching?',
                               'age_60_and_above':'Are you above 60?',
                               'gender':'What is your gender',
                               'test_indication':'Have you been in contact with any person who has covid in last 14 days?'
                               }
                for key, question in userQuestionDisct.items():
                    print(chatBotName +" : "+question)
                    userInput = input()                
                    if (userInput.lower() == 'yes') | (userInput.lower() == 'male'):
                        userInputDict[key] = 1
                    elif (userInput.lower() == 'no') | (userInput.lower() == 'female'):
                        userInputDict[key] = 0
                    else:
                        print(chatBotName +" : sorry i did not understand this, can you answer in yes or no?")
                new_x_list = []
                for value in userInputDict.values():
                    new_x_list.append(value)
                new_array = np.array(new_x_list)
                predict_result = nn.predict(new_array.reshape(1, -1))
                if predict_result[0] == 1:
                    print(chatBotName +" : It looks like you have covid symptons, we will recommend you to get tested at near COVID Center, here is list of all COVID test center:\n https://covid-19.ontario.ca/assessment-centre-locations")
                else:
                    print(chatBotName +" : From information you have shared, we feel you are noy still infected with COVID, however, we will recommed you to isolate yourself and take proper precautions")
        
            

In [293]:
COVIDChatbot()

COVBOT : Hey There
hey
User : hey
['hey']
COVBOT : Ok I will ask you some questions to check if you are positive or not
COVBOT : Do you have any cough?
yes
COVBOT : Do you have fever?
yes
COVBOT : Do you have sore throat?
yes
COVBOT : Do you have shprtness of breath?
no
COVBOT : Is your head aching?
yes
COVBOT : Are you above 60?
no
COVBOT : What is your gender
male
COVBOT : Have you been in contact with any person who has covid in last 14 days?
yes
COVBOT : It looks like you have covid symptons, we will recommend you to get tested at near COVID Center, here is list of all COVID test center:
 https://covid-19.ontario.ca/assessment-centre-locations
COVBOT : Ok I will ask you some questions to check if you are positive or not
COVBOT : Do you have any cough?


KeyboardInterrupt: Interrupted by user